name: Machine Learning CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      run: python -m unittest discover
    
    - name: Train and Evaluate Model
      run: python ml_model.py

    - name: Save Model Artifact
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: model.npy
